import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
import Nav from '../components/Nav'
import Projects from '../components/projects/ProjectList'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div className='dark max-w-7xl mx-auto h-screen px-10 sm:px-8 lg:px-40'>
      <Head>
        <title>Naomi Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Nav /> 

      <section id='hero' className="sm:h-screen pt-36">
        <Hero/>
      </section>

      <section id='about' className="sm:h-screen pt-32">
        <About/>
      </section>

      <section id='skills' className="sm:h-screen pt-32">
        <Skills />
      </section>

      <section id='projects' className="sm:h-screen pt-32">
        <Projects />
      </section>

      <section id='contact' className="h-screen pt-32 sm:pt-56 lg:pt-40">
        <Contact />
      </section>

    </div>
  )
}
